services:
  postgres:
    image: postgres:16
    container_name: postgres_servidor
    restart: always
    environment:
      POSTGRES_DB: projetointegrador
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: e3d4r35tsq354d2E
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
